import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { BrowserRouter, Route, Routes } from "react-router-dom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <React.StrictMode>
      // <BrowserRouter>
    <html lang="en">
     
      <body className={inter.className}>
      <NavBar /> 
        {children} 
     
        <Footer />
      </body>
      
    </html>
    // </BrowserRouter>
    // </React.StrictMode>
  );
}
