import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { BrowserRouter, Route, Routes } from "react-router-dom";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
     <head><link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@900&family=Itim&display=swap" rel="stylesheet"/>
</head>

      <body>
      <NavBar /> 
      <div className="maincontainer">
        {children} 
        </div>
     
        <Footer />
      </body>
      
    </html>


  );
}
